version: '3.2'
services:
 dev_my-client:
  command: npm start
  build:
   context: ./client
   dockerfile: Dockerfile
  image: client-img
  volumes:
   - './client:/usr/src/app'
   - '/usr/src/app/node_modules'
  ports:
   - '3000:3000'
  depends_on:
   - 'web_dev'
  environment:
   - NODE_ENV=development


 web_dev:
  build: .
  image: server-img
  ports:
   - '5000:5000'
  volumes:
   - '.:/usr/src/app'
  environment:
   - ENV=development
   - DB=mongodb://mongodb:27017/development
   - PORT=5000
   - HOST=0.0.0.0
  depends_on:
   - "mongodb"

 mongodb:
  image: mongo:latest
  container_name: "mongodb"
  environment:
   - MONGO_DATA_DIR=/usr/data/db
   - MONGO_LOG_DIR=/dev/null
  volumes:
   - ./data/db:/usr/data/db
  ports:
   - 27017:27017
  command: mongod --smallfiles --logpath=/dev/null # --quiet